"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 22:31:15.350851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# users.firm_id -> firms and firms.reviewed_by_id -> users form a cycle, so the latter FK is
# added after both tables exist. (op.create_table silently skips `use_alter` constraints.)
FIRM_REVIEWER_FK = "fk_firms_reviewed_by_id_users"


def _supports_alter_fk() -> bool:
    return op.get_context().dialect.name != "sqlite"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('code', name=op.f('uq_cities_code'))
    )
    op.create_table('request_statuses',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_request_statuses'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('super_admin', 'operations', 'firm_manager', 'hr_dispatcher', 'facility_manager', 'site_supervisor', 'security_guard', name='role_code'), nullable=False),
    sa.Column('portal', sa.Enum('platform', 'firm', 'client', 'mobile', name='portal'), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('code', name=op.f('uq_sectors_code'))
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('geofence_radius_m > 0', name=op.f('ck_facilities_positive_geofence_radius')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_facilities_valid_latitude')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_facilities_valid_longitude')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_facilities_city_id_cities')),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_facilities_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_index(op.f('ix_facilities_city_id'), 'facilities', ['city_id'], unique=False)
    op.create_index(op.f('ix_facilities_sector_id'), 'facilities', ['sector_id'], unique=False)
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('moi_license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('commercial_registration', sa.String(length=20), nullable=True),
    sa.Column('headquarters_city_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('total_guards', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='firm_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('total_guards >= 0', name=op.f('ck_firms_total_guards_non_negative')),
    sa.ForeignKeyConstraint(['headquarters_city_id'], ['cities.id'], name=op.f('fk_firms_headquarters_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firms')),
    sa.UniqueConstraint('commercial_registration', name=op.f('uq_firms_commercial_registration')),
    sa.UniqueConstraint('moi_license_number', name=op.f('uq_firms_moi_license_number'))
    )
    op.create_index(op.f('ix_firms_headquarters_city_id'), 'firms', ['headquarters_city_id'], unique=False)
    op.create_index(op.f('ix_firms_status'), 'firms', ['status'], unique=False)
    op.create_table('firm_cities',
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_firm_cities_city_id_cities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_firm_cities_firm_id_firms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('firm_id', 'city_id', name=op.f('pk_firm_cities'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('preferred_locale', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('firm_id IS NULL OR facility_id IS NULL', name=op.f('ck_users_single_organization')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_users_facility_id_facilities')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_users_firm_id_firms')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_facility_id'), 'users', ['facility_id'], unique=False)
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    if _supports_alter_fk():
        op.create_foreign_key(FIRM_REVIEWER_FK, 'firms', 'users', ['reviewed_by_id'], ['id'])
    op.create_table('guard_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guard_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('daily_hours', sa.Integer(), nullable=False),
    sa.Column('bidding_deadline', sa.DateTime(), nullable=True),
    sa.Column('budget_per_guard', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('daily_hours BETWEEN 1 AND 24', name=op.f('ck_guard_requests_valid_daily_hours')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_guard_requests_valid_period')),
    sa.CheckConstraint('guard_count > 0', name=op.f('ck_guard_requests_positive_guard_count')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_guard_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_guard_requests_facility_id_facilities')),
    sa.ForeignKeyConstraint(['status_code'], ['request_statuses.code'], name=op.f('fk_guard_requests_status_code_request_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_requests'))
    )
    op.create_index(op.f('ix_guard_requests_facility_id'), 'guard_requests', ['facility_id'], unique=False)
    op.create_index(op.f('ix_guard_requests_status_code'), 'guard_requests', ['status_code'], unique=False)
    op.create_table('guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('full_name_ar', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.Enum('active', 'on_leave', 'terminated', name='employment_status'), nullable=False),
    sa.Column('shamoos_status', sa.Enum('pending', 'verified', 'rejected', name='shamoos_status'), nullable=False),
    sa.Column('shamoos_checked_at', sa.DateTime(), nullable=True),
    sa.Column('shamoos_reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_guards_city_id_cities')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_guards_firm_id_firms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_guards_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guards')),
    sa.UniqueConstraint('national_id', name=op.f('uq_guards_national_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_guards_user_id'))
    )
    op.create_index(op.f('ix_guards_city_id'), 'guards', ['city_id'], unique=False)
    op.create_index('ix_guards_firm_availability', 'guards', ['firm_id', 'shamoos_status', 'employment_status'], unique=False)
    op.create_index(op.f('ix_guards_firm_id'), 'guards', ['firm_id'], unique=False)
    op.create_index(op.f('ix_guards_shamoos_status'), 'guards', ['shamoos_status'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('price_per_guard', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'accepted', 'rejected', 'withdrawn', name='bid_status'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price_per_guard > 0', name=op.f('ck_bids_positive_price')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_bids_firm_id_firms')),
    sa.ForeignKeyConstraint(['request_id'], ['guard_requests.id'], name=op.f('fk_bids_request_id_guard_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_bids_submitted_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids')),
    sa.UniqueConstraint('request_id', 'firm_id', name='uq_bids_request_firm')
    )
    op.create_index(op.f('ix_bids_firm_id'), 'bids', ['firm_id'], unique=False)
    op.create_index(op.f('ix_bids_request_id'), 'bids', ['request_id'], unique=False)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_table('shamoos_verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('verified', 'rejected', 'error', name='shamoos_check_result'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], name=op.f('fk_shamoos_verification_logs_guard_id_guards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_shamoos_verification_logs_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shamoos_verification_logs'))
    )
    op.create_index(op.f('ix_shamoos_verification_logs_created_at'), 'shamoos_verification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_shamoos_verification_logs_guard_id'), 'shamoos_verification_logs', ['guard_id'], unique=False)
    op.create_index(op.f('ix_shamoos_verification_logs_national_id'), 'shamoos_verification_logs', ['national_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=30), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sla_breach_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('sla_penalty_per_breach', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sla_max_penalty_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sla_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending_firm_signature', 'pending_facility_approval', 'active', 'completed', 'terminated', name='contract_status'), nullable=False),
    sa.Column('firm_signed_by_id', sa.Integer(), nullable=True),
    sa.Column('firm_signed_at', sa.DateTime(), nullable=True),
    sa.Column('facility_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('facility_approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], name=op.f('fk_contracts_bid_id_bids')),
    sa.ForeignKeyConstraint(['facility_approved_by_id'], ['users.id'], name=op.f('fk_contracts_facility_approved_by_id_users')),
    sa.ForeignKeyConstraint(['firm_signed_by_id'], ['users.id'], name=op.f('fk_contracts_firm_signed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('bid_id', name=op.f('uq_contracts_bid_id')),
    sa.UniqueConstraint('contract_number', name=op.f('uq_contracts_contract_number'))
    )
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'overdue', 'cancelled', name='invoice_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_invoices_contract_id_contracts')),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], name=op.f('fk_invoices_paid_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('contract_id', 'period_start', name='uq_invoices_contract_period'),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'missed', 'cancelled', name='shift_status'), nullable=False),
    sa.Column('clock_in_at', sa.DateTime(), nullable=True),
    sa.Column('clock_in_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('clock_in_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('clock_out_at', sa.DateTime(), nullable=True),
    sa.Column('clock_out_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('clock_out_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_location_at', sa.DateTime(), nullable=True),
    sa.Column('geofence_breach_flag', sa.Boolean(), nullable=False),
    sa.Column('breach_active_since', sa.DateTime(), nullable=True),
    sa.Column('breach_total_minutes', sa.Integer(), nullable=False),
    sa.Column('penalty_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('scheduled_end > scheduled_start', name=op.f('ck_shifts_valid_schedule')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_shifts_assigned_by_id_users')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_shifts_contract_id_contracts')),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], name=op.f('fk_shifts_guard_id_guards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index('ix_shifts_breach_scan', 'shifts', ['geofence_breach_flag', 'penalty_flagged'], unique=False)
    op.create_index(op.f('ix_shifts_contract_id'), 'shifts', ['contract_id'], unique=False)
    op.create_index('ix_shifts_guard_schedule', 'shifts', ['guard_id', 'scheduled_start'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', name='incident_status'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], name=op.f('fk_incidents_guard_id_guards')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_incidents_reviewed_by_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_incidents_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_guard_id'), 'incidents', ['guard_id'], unique=False)
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_shift_id'), 'incidents', ['shift_id'], unique=False)
    op.create_table('sla_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('breach_minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'waived', name='penalty_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_sla_penalties_contract_id_contracts')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_sla_penalties_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_sla_penalties_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_penalties')),
    sa.UniqueConstraint('shift_id', name=op.f('uq_sla_penalties_shift_id'))
    )
    op.create_index(op.f('ix_sla_penalties_contract_id'), 'sla_penalties', ['contract_id'], unique=False)
    op.create_index(op.f('ix_sla_penalties_invoice_id'), 'sla_penalties', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _supports_alter_fk():
        op.drop_constraint(FIRM_REVIEWER_FK, 'firms', type_='foreignkey')
    op.drop_index(op.f('ix_sla_penalties_invoice_id'), table_name='sla_penalties')
    op.drop_index(op.f('ix_sla_penalties_contract_id'), table_name='sla_penalties')
    op.drop_table('sla_penalties')
    op.drop_index(op.f('ix_incidents_shift_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_guard_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_shifts_guard_schedule', table_name='shifts')
    op.drop_index(op.f('ix_shifts_contract_id'), table_name='shifts')
    op.drop_index('ix_shifts_breach_scan', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_shamoos_verification_logs_national_id'), table_name='shamoos_verification_logs')
    op.drop_index(op.f('ix_shamoos_verification_logs_guard_id'), table_name='shamoos_verification_logs')
    op.drop_index(op.f('ix_shamoos_verification_logs_created_at'), table_name='shamoos_verification_logs')
    op.drop_table('shamoos_verification_logs')
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index(op.f('ix_bids_request_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_firm_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_guards_shamoos_status'), table_name='guards')
    op.drop_index(op.f('ix_guards_firm_id'), table_name='guards')
    op.drop_index('ix_guards_firm_availability', table_name='guards')
    op.drop_index(op.f('ix_guards_city_id'), table_name='guards')
    op.drop_table('guards')
    op.drop_index(op.f('ix_guard_requests_status_code'), table_name='guard_requests')
    op.drop_index(op.f('ix_guard_requests_facility_id'), table_name='guard_requests')
    op.drop_table('guard_requests')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.drop_index(op.f('ix_users_facility_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('firm_cities')
    op.drop_index(op.f('ix_firms_status'), table_name='firms')
    op.drop_index(op.f('ix_firms_headquarters_city_id'), table_name='firms')
    op.drop_table('firms')
    op.drop_index(op.f('ix_facilities_sector_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_city_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_table('sectors')
    op.drop_table('roles')
    op.drop_table('request_statuses')
    op.drop_table('cities')
    # ### end Alembic commands ###
